name = "KumulalaCraft2"
author = "Ciszek"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "179045dc767ef00de235698c651a19d43ea529aabff6fa76e918a5615b0905e3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"
