name = "KumulalaCraft2"
author = "Ciszek"
version = "0.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8667ed51bcce1137447cfde10b3e74b04adc1ef031eb6802dfc190bbf387ce9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"
