name = "KumulalaCraft2"
author = "Ciszek"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d65fe83de845b96fdccc52202cd6db1a1be0c5f426af02a0ede8a44e3b82060"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"
